import { getPerShareRatioDescription } from "../functions/getDescription";

const extractBeforePerShare = (input: string): string => {
    const convertToLowerCase = input.toLowerCase();
    const indexOfPerShare = convertToLowerCase.indexOf("per share");
    return indexOfPerShare !== -1 ? input.substring(0, indexOfPerShare) : input;
}

const acronymn = (input: string): string => {
    return input.split(" ").map(w => w[0]).join("");
}

export const perShareRatio = (metricValue: string, metricName: string): string =>
    `${metricName} (${acronymn(metricName)}) of $${metricValue} reflects the company's ${extractBeforePerShare(metricName)} generated per outstanding share. <br><br>
${metricName} is a financial ratio that measures the amount of ${extractBeforePerShare(metricName)}generated by a company for each outstanding share of stock over a certain 
period of time (in this case trailing twelve months). In general, the higher the ${acronymn(metricName)}, the more efficient a company is at generating ${extractBeforePerShare(metricName)}.
<br><br>

A single ${acronymn(metricName)} value is arbitrary and its significance dependends on a variety of factors:
<ul>
    <li>Context: Industry norms and the company's business model.</li>
    <li>Trends: Whether the ratio is improving or declining over time.</li>
    <li>Peers: Comparison with similar companies.</li>
</ul>
${getPerShareRatioDescription(metricName)}
`;

export const earningsYield = (metricValue: string, metricName: string): string =>
    `${metricName} (${acronymn(metricName)}) of ${metricValue} means for every $1 invested, the stock generates ${metricValue} cents. <br/><br/>

    Earnings yield is a valuation metric that helps investors assess the return generated by a company relative to its stock price. Earnings yield 
    shows how much earnings per share a company generates for every dollar invested in the company's stock and is calculated by the TTM 
    Earnings Per Share divided by the current market price per share. <br />
    The trend in earnings yield can provide insights into a company's valuation, growth prospects, and market sentiments.<br /><br/>

    Rising Earnings Yield:
    <ul>
        <li>
            If the yield is increasing over time, it may indicate that the company's earnings are growing faster than its stock price, suggesting that 
            the stock might be undervalued. This could also mean the company is generating stronger earnings, which could be a positive sign for investors.
        </li>
        <li>
            Conversely, if the yield is increasing over time due to dips in the stock price, the reason for this decrease should be investigated. A short-term 
            pullback in the stock price can indicate a buying opportunity; a long-term decline is something to avoid. While a falling stock price increases the 
            earnings yield in technical terms, it often reflects decreased investor confidence, typically due to poor financial performance or negative future prospects.
        </li> 
    </ul>

    Declining Earnings Yield:
    <ul>
        <li>
            A declining earnings yield may signal that the stock price is rising faster than earnings, potentially suggesting that the stock is becoming overvalued.
        </li>
        <li>
            A falling earnings yield could also reflect stagnating or decreasing earnings while the stock price remains elevated.
        </li>
    <ul>
`;

export const freeCashflowYield = (metricValue: string, metricName: string): string =>
    `${metricName} (${acronymn(metricName)}) of ${metricValue} means for every $1 invested, the company generates ${metricValue} of it's market value in free 
    cash flow. <br/><br/>
    
    Free cash flow yield is a solvency ratio that compares the free cash flow per share a company is expected to earn against its market value per share. 
    It is calculated by taking the a company's TTM Free Cash Flow and dividing it by its market capitalisation. <br/>
    
    A higher FCF Yield is a positive sign that indicates a more attractive investment opportunity, as it signifies that a company is generating significant 
    cash flow to meet all its obligations. It suggests that investors are getting a good return on their investment. 

    A high FCF Yield demonstrates that a company can comfortably manage its debt, cover other obligations, and provide dividend payouts.
    Conversely, a low FCF Yield indicates that investors might not be receiving a satisfactory return, making the company less attractive as an investment. 
    `;

export const returnRatio = (metricValue: string, metricName: string, type: string): string => {

    const name = metricName !== "ROE" ? acronymn(metricName) : metricName
    const description = `${metricName} ${metricName !== "ROE" ? `(${acronymn(metricName)})` : `(${metricName})`} of ${metricValue} means for every $1 of ${type}, 
    the company generates $${metricValue} of profit. 
    <br/><br/>
    ${name} is a key metric for understanding a company's financial perforamce and how effectively it is utilising its ${type} to generate earnings. Put simply, 
    the higher the ${name} the more effective a company is at generating income from it's ${type}. <br /><br />

    Whether an ${name} is deemed good or bad will depend on what is normal among a stock’s peers. A good rule of thumb is to compare ${name} to industry peers rather 
    than using a fixed benchmark. <br/><br/>

    If a company has a negative ${name}, it indicates income was negative for the year. This may indicate a sign of financial distress, but can also mean 
    the company is in a growth phase or investing heavily in its future, such as through research and development or expansion 
    which may result in short-term losses but lead to long-term profitability. This pattern is common among younger companies and start-ups.
    `;

    return description
}


